[default]
src = 'src/'
out = 'out/'
libs = ['lib', 'node_modules']
gas_reports = ["*"]
optimizer = true
optimizer_runs = 20000


# Remappings in remappings.txt

# See more config options https://github.com/gakonst/foundry/tree/master/config